/**
 * Data Migrations — one-time data transformations tracked in the DataMigration table.
 *
 * HOW TO ADD A NEW MIGRATION:
 *   1. Add a new entry to MIGRATIONS below (keep them in chronological order)
 *   2. Use a unique `id` in the format "YYYY-MM-DD-description"
 *   3. The `run` function receives the Prisma client and must be idempotent
 *      (safe to run multiple times with no side effects if it already ran)
 *   4. The runner marks it as done after success — it will NEVER run again
 *
 * Migrations run automatically on the first request after a deploy
 * (called from api/src/lib/startup.ts, triggered by db.ts import).
 */

import type { PrismaClient } from '../generated/prisma/client'

interface Migration {
  id:  string
  run: (db: PrismaClient) => Promise<void>
}

const MIGRATIONS: Migration[] = [
  // ─── 2026-06-02 ─────────────────────────────────────────────────────
  {
    id:  '2026-06-02-migrate-recurring-bills',
    run: async (db) => {
      // Converts old Bill.isRecurring=true records into RecurringBill templates.
      // Groups bills by (userId, name) — each unique name becomes one template.
      // Links existing bills to their template via recurringBillId.
      const bills = await db.bill.findMany({
        where:   { isRecurring: true, recurringBillId: null },
        orderBy: { dueDate: 'desc' },
      })

      const byUserName = new Map<string, typeof bills>()
      for (const b of bills) {
        const key = `${b.userId}::${b.name}`
        const arr = byUserName.get(key) ?? []
        arr.push(b)
        byUserName.set(key, arr)
      }

      for (const [, group] of byUserName.entries()) {
        const latest = group[0]
        const day    = Math.min(new Date(latest.dueDate).getUTCDate(), 28)

        const template = await db.recurringBill.create({
          data: {
            name:       latest.name,
            amount:     latest.amount,
            dayOfMonth: day,
            userId:     latest.userId,
            categoryId: latest.categoryId ?? null,
            notes:      latest.notes ?? null,
          },
        })

        await db.bill.updateMany({
          where: { id: { in: group.map(b => b.id) } },
          data:  { recurringBillId: template.id, isRecurring: false },
        })
      }
    },
  },

  // ─── 2026-06-03 ─────────────────────────────────────────────────────
  {
    id:  '2026-06-03-dedup-recurring-person-entries',
    run: async (db) => {
      // The old "Pago" button on RecurringEntryCard created a NEW PersonEntry
      // instead of settling the existing generated one. This left duplicate
      // unsettled entries (same person + description + month). Keep the oldest
      // (generated by cron) and delete the duplicates created by the button.
      const entries = await db.personEntry.findMany({
        where:   { isSettled: false, installmentGroupId: null },
        orderBy: { createdAt: 'asc' },
        select:  { id: true, personId: true, userId: true, type: true, description: true, amount: true, date: true, createdAt: true },
      })

      // Group by userId + personId + description + type + year-month
      const groups = new Map<string, typeof entries>()
      for (const e of entries) {
        const month = `${new Date(e.date).getFullYear()}-${String(new Date(e.date).getMonth() + 1).padStart(2, '0')}`
        const key   = `${e.userId}::${e.personId}::${e.description}::${e.type}::${month}`
        const arr   = groups.get(key) ?? []
        arr.push(e)
        groups.set(key, arr)
      }

      const toDelete: string[] = []
      for (const [, group] of groups.entries()) {
        if (group.length <= 1) continue
        // Keep the first (oldest/cron-generated), delete the rest
        toDelete.push(...group.slice(1).map(e => e.id))
      }

      if (toDelete.length > 0) {
        await db.personEntry.deleteMany({ where: { id: { in: toDelete } } })
        console.log(`[data-migration] dedup: removed ${toDelete.length} duplicate person entries`)
      }
    },
  },

  // ─── 2026-06-03 ─────────────────────────────────────────────────────
  {
    id:  '2026-06-03-invalidate-plain-text-reset-tokens',
    run: async (db) => {
      // passwordResetToken now stores SHA-256 hashes.
      // Any existing plain-text tokens are invalid — clear them so users
      // can't use old unscoped links. They'll request a new reset link.
      await db.user.updateMany({
        where: { passwordResetToken: { not: null } },
        data:  { passwordResetToken: null, passwordResetExpiry: null },
      })
    },
  },

  // ─── 2026-06-03 ─────────────────────────────────────────────────────
  {
    id:  '2026-06-03-clear-test-stripe-customer-ids',
    run: async (db) => {
      // When we switched from Stripe test mode to production, some users
      // had test-mode stripeCustomerId (cus_...) stored. These are invalid
      // in production. Clear them so the billing portal check works correctly.
      // Users will get a new customerId when they subscribe in production.
      await db.user.updateMany({
        where: { stripeCustomerId: { not: null } },
        data:  { stripeCustomerId: null, stripeSubscriptionId: null },
      })
    },
  },

  // ─── 2026-06-05 ─────────────────────────────────────────────────────
  {
    id:  '2026-06-05-revert-future-startdate-income',
    run: async (db) => {
      // Reverts income transactions incorrectly created for sources with a future startDate.
      // This happened because processAutoIncome() didn't check startDate before this fix.
      const now        = new Date()
      const yearMonth  = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
      const monthStart = new Date(now.getFullYear(), now.getMonth(), 1)
      const monthEnd   = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59)

      const sources = await db.incomeSource.findMany({
        where: {
          startDate:        { gt: now },    // startDate is in the future
          lastAutoPayMonth: yearMonth,      // but was processed this month (bug)
        },
      })

      for (const src of sources) {
        await db.transaction.deleteMany({
          where: {
            userId:      src.userId,
            type:        'INCOME',
            description: src.name,
            date:        { gte: monthStart, lte: monthEnd },
          },
        })
        await db.incomeSource.update({
          where: { id: src.id },
          data:  { lastAutoPayMonth: null },
        })
      }
    },
  },
]

// ─── Runner ──────────────────────────────────────────────────────────────────

let started = false // module-level: prevents duplicate runs within the same process

export async function runDataMigrations(db: PrismaClient): Promise<void> {
  if (started) return
  started = true

  try {
    const done = new Set(
      (await db.dataMigration.findMany({ select: { id: true } })).map(m => m.id)
    )

    for (const migration of MIGRATIONS) {
      if (done.has(migration.id)) continue

      try {
        await migration.run(db)
        await db.dataMigration.create({ data: { id: migration.id } })
        console.log(`[data-migration] ✓ ${migration.id}`)
      } catch (err) {
        // Log but don't crash — a failed migration will retry on next deploy
        console.error(`[data-migration] ✗ ${migration.id}:`, err)
        started = false // allow retry on next request
      }
    }
  } catch (err) {
    console.error('[data-migration] runner failed:', err)
    started = false
  }
}
