import { withBackofficeAuth } from '@/lib/middleware'
import { db } from '@/lib/db'
import { ok } from '@/lib/respond'

export default withBackofficeAuth(async (_req, res) => {
  const notBot = { NOT: { email: { startsWith: 'bot-' } } } as const

  const [
    totalUsers,
    dripDay1,
    dripDay3,
    dripDay7,
    promoDay14,
    promoDay30,
    promoDay60,
    inactivitySent,
    freeUsers,
    usersWithActivity,
    usersInactive7d,
  ] = await Promise.all([
    db.user.count({ where: notBot }),
    db.user.count({ where: { ...notBot, lastDripEmailDay: { gte: 1 } } }),
    db.user.count({ where: { ...notBot, lastDripEmailDay: { gte: 3 } } }),
    db.user.count({ where: { ...notBot, lastDripEmailDay: 7 } }),
    db.user.count({ where: { ...notBot, lastPromoEmailDay: { gte: 14 } } }),
    db.user.count({ where: { ...notBot, lastPromoEmailDay: { gte: 30 } } }),
    db.user.count({ where: { ...notBot, lastPromoEmailDay: 60 } }),
    db.user.count({ where: { ...notBot, lastInactivityEmail: { not: null } } }),
    db.user.count({ where: { ...notBot, plan: 'FREE' } }),
    db.user.count({ where: { ...notBot, lastActiveAt: { not: null } } }),
    db.user.count({
      where: {
        ...notBot,
        lastActiveAt: { not: null, lte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
      },
    }),
  ])

  const flows = [
    {
      id: 'welcome',
      name: 'Boas-vindas',
      trigger: 'Ao criar conta',
      description: 'Email com Rookinho, features e CTA pro dashboard',
      sent: null,
      audience: 'Todos os novos usuários',
      type: 'transactional' as const,
    },
    {
      id: 'drip-d1',
      name: 'Onboarding D+1',
      trigger: '1 dia após cadastro',
      description: 'Incentiva a registrar o primeiro gasto',
      sent: dripDay1,
      audience: 'Novos cadastros',
      type: 'lifecycle' as const,
    },
    {
      id: 'drip-d3',
      name: 'Onboarding D+3',
      trigger: '3 dias após cadastro',
      description: 'Incentiva a criar primeira meta financeira',
      sent: dripDay3,
      audience: 'Novos cadastros',
      type: 'lifecycle' as const,
    },
    {
      id: 'drip-d7',
      name: 'Onboarding D+7',
      trigger: '7 dias após cadastro',
      description: 'Apresenta o Rookinho IA',
      sent: dripDay7,
      audience: 'Novos cadastros',
      type: 'lifecycle' as const,
    },
    {
      id: 'conversion-d14',
      name: 'Conversão D+14',
      trigger: '14 dias após cadastro',
      description: 'Social proof + features PRO desbloqueadas',
      sent: promoDay14,
      audience: `FREE (${freeUsers})`,
      type: 'conversion' as const,
    },
    {
      id: 'conversion-d30',
      name: 'Conversão D+30',
      trigger: '30 dias após cadastro',
      description: 'Stats pessoais de uso + comparação de preço',
      sent: promoDay30,
      audience: `FREE (${freeUsers})`,
      type: 'conversion' as const,
    },
    {
      id: 'conversion-d60',
      name: 'Conversão D+60',
      trigger: '60 dias após cadastro',
      description: 'Urgência + PRO+ highlight',
      sent: promoDay60,
      audience: `FREE (${freeUsers})`,
      type: 'conversion' as const,
    },
    {
      id: 'inactivity',
      name: 'Reengajamento',
      trigger: '7+ dias sem login',
      description: 'Email "cadê você?" com sugestões de ação',
      sent: inactivitySent,
      audience: `Inativos 7d+ (${usersInactive7d})`,
      type: 'reengagement' as const,
    },
    {
      id: 'upgrade',
      name: 'Upgrade PRO',
      trigger: 'Checkout Stripe concluído',
      description: 'Parabéns + features desbloqueadas',
      sent: null,
      audience: 'Novos assinantes',
      type: 'transactional' as const,
    },
    {
      id: 'downgrade',
      name: 'Cancelamento',
      trigger: 'Assinatura Stripe encerrada',
      description: '"Sentiremos sua falta" + CTA reativar',
      sent: null,
      audience: 'Ex-assinantes',
      type: 'transactional' as const,
    },
    {
      id: 'goal-completed',
      name: 'Meta atingida',
      trigger: 'Aporte que completa meta',
      description: 'Parabéns com valor e CTA pra nova meta',
      sent: null,
      audience: 'Quem atinge 100% de uma meta',
      type: 'transactional' as const,
    },
    {
      id: 'achievement',
      name: 'Conquista desbloqueada',
      trigger: 'Unlock de achievement',
      description: 'Notificação da conquista com ícone',
      sent: null,
      audience: 'Todos com achievements',
      type: 'transactional' as const,
    },
    {
      id: 'anniversary',
      name: 'Aniversário de conta',
      trigger: 'Aniversário de 1+ anos',
      description: 'Celebração com agradecimento',
      sent: null,
      audience: 'Usuários com 1+ ano',
      type: 'lifecycle' as const,
    },
    {
      id: 'annual-upsell',
      name: 'Upsell anual',
      trigger: 'Dia 15, 3+ meses no mensal',
      description: 'Comparação mensal vs anual com economia',
      sent: null,
      audience: 'PRO/PRO+ mensal 3+ meses',
      type: 'conversion' as const,
    },
    {
      id: 'bill-reminder',
      name: 'Lembrete de contas',
      trigger: 'Cron — contas em 2-3 dias',
      description: 'Tabela de contas vencendo com CTA',
      sent: null,
      audience: 'Quem tem contas vencendo',
      type: 'transactional' as const,
    },
    {
      id: 'monthly-summary',
      name: 'Resumo mensal',
      trigger: 'Cron — dia 1 do mês',
      description: 'Receitas, despesas e saldo do mês anterior',
      sent: null,
      audience: 'Opt-in',
      type: 'lifecycle' as const,
    },
    {
      id: 'payment-failed',
      name: 'Falha no pagamento',
      trigger: 'Webhook Stripe',
      description: 'Aviso para atualizar forma de pagamento',
      sent: null,
      audience: 'Assinantes com falha',
      type: 'transactional' as const,
    },
    {
      id: 'pro-expiry',
      name: 'Expiração PRO manual',
      trigger: 'Cron — 3 dias antes e no dia',
      description: 'Aviso de que o acesso PRO manual expira',
      sent: null,
      audience: 'PRO manual com data',
      type: 'transactional' as const,
    },
    {
      id: 'password-reset',
      name: 'Redefinir senha',
      trigger: 'Formulário "esqueci a senha"',
      description: 'Link de reset com token de 1h',
      sent: null,
      audience: 'Quem solicitar',
      type: 'transactional' as const,
    },
    {
      id: 'newsletter',
      name: 'Newsletter',
      trigger: 'Novo artigo do blog',
      description: 'Preview do artigo com CTA',
      sent: null,
      audience: 'Inscritos na newsletter',
      type: 'marketing' as const,
    },
    {
      id: 'churn-alert',
      name: 'Alerta de churn',
      trigger: 'Cron — dia 2 se threshold excedido',
      description: 'Alerta admin de downgrades',
      sent: null,
      audience: 'Admin',
      type: 'internal' as const,
    },
  ]

  return ok(res, { flows, totalUsers, freeUsers, usersWithActivity, usersInactive7d })
})
